apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: Capstone
  region: us-east-2

nodeGroups:
  - name: blue
    instanceType: t2.micro
    minSize: 1
    desiredCapacity: 2
    maxSize: 4
    labels:
      nodegroup-type: blue-workers
      node-class: "blue-workers"
    iam:
      withAddonPolicies:
        autoScaler: true
