apiVersion: apps/v1
kind: Deployment
metadata:
  name: cyan-green-deployment
  labels:
    app: cyan-green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cyan-green
  template:
    metadata:
      labels:
        app: cyan-green
    spec:
      containers:
      - name: cyan-green
        image: scgerkin/cyan-app:0.0.2-green
        node-class: "green-workers"
        ports:
        - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: cyanlb-green
  labels:
    app: cyanlb-green
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: cyan-green
  type: LoadBalancer
